/**
 * The sentences the code workspace shows on a control that cannot be used.
 *
 * Presentation layer: strings only. They live here because the same two actions
 * (Format and Reset for the props payload) exist twice on screen — once in the
 * editor tab strip and once in the right-rail card — and two copies of a
 * sentence drift apart. See `shared/ReasonedButton.tsx` for the pattern.
 */

/** Reset, when the tab or card has no local edits to throw away. */
export const NOTHING_TO_RESET_REASON = 'There are no local changes to reset.'

/** Format, when the JSON cannot be parsed and so cannot be pretty-printed. */
export const INVALID_JSON_FORMAT_REASON = 'The payload has to be valid JSON before it can be formatted.'

/** Format, on a tab whose text the render produced rather than a person. */
export const READ_ONLY_FORMAT_REASON = 'This tab is generated by the render, so there is nothing to format.'

/** Reset, on a tab whose text the render produced rather than a person. */
export const READ_ONLY_RESET_REASON = 'This tab is generated by the render, so there is nothing to reset.'
